### ISSUE TITLE
Redundant listing

### ISSUE THREAD

**Issue by Dook42** [thecodeflayer/alttp-tracker#20]
Uncle and Secret Passage entries are for the same area. They're listing makes it seem like there's 3 total items there when there's actually only 2.

**Comment by attensityrjones** [comment]
I actually have a fix for this in the inverted code branch. Thanks for confirming my suspicions. I've modified it to be only one item each and the remaining items from escape are on "Back of Escape" entry. Once I have inverted mode completed this fix will be included.

**Comment by thecodeflayer** [comment]
I actually have a fix for this in the inverted code branch. Thanks for confirming my suspicions. I've modified it to be only one item each and the remaining items from escape are on "Back of Escape" entry. Once I have inverted mode completed this fix will be included.
