### ISSUE TITLE
Inverted Bugs

### ISSUE THREAD

**Issue by Dook42** [thecodeflayer/alttp-tracker#28]
I'm by no means an expert, but during a recent run here are a few things I saw that I believe to be bugs:

All for inverted mode on 0.9.6:
- No Link's house check
- Pyramid listed as immediately available, as far as I know you need either hammer or flippers
- Having flippers turns Swamp blue, even tho you can't do anything there (besides check the hint tile, which doesn't need flippers lol) without light world access & mirror.
- Also you need hookshot to get to Swamp boss (and the back in general), but it turns blue without it
- Similarly POD boss is inaccessible without bow
- Ice palace doesn't need mitts when inverted
- Desert palace and ledge both require book
- Bomb merchant is listed as a check, guessing this is the missing Link's house one
- Secret Passage & sanctuary both should require moon pearl
- Inverted Aga1 (moves to GT) is accessible as soon as death mountain access is gained, but currently only lights up with 7 crystals

**Comment by thecodeflayer** [comment]
I'll get these looked at as soon as I can.
