### ISSUE TITLE
Reason behind decrementing keys

### ISSUE THREAD

**Issue by hellow554** [thecodeflayer/alttp-tracker#41]
I'm somewhat confused why clicking on a key counts downwards.
If I'm for example in Keysanity mode I want to track the amount of keys I already collected.

So, what's the reason? Is there a Chance to add an Option to increment keys in click?

**Comment by thecodeflayer** [comment]
Keys only decrement when the item shuffle setting is set to standard. If you create a new game under Settings, you can select the Keysanity option under item shuffle and the keys will increment in that mode. More information about how item shuffle settings work can be found here: https://github.com/thecodeflayer/alttp-tracker/blob/master/FAQ.md#item-shuffle-settings

I'll get this question added to the FAQ page as well.
